### ISSUE TITLE
Support tagging in new repos with no pre-existing tags

### ISSUE THREAD

**Issue by mdwhatcott** [smartystreets/version-tools#2]
What is the expected behavior of `tagit -M` on a new git repository with a single, initial commit?

What I’m seeing, regardless of which flag I use (-M, -m, or -p) is this:

```
No changes to repository since last tag '0.0.0'.
```

It doesn’t add a tag at this point. So `git tag` still lists nothing and `git describe` shows `fatal: No names found, cannot describe anything.`

```
$ git init
$ git add
$ git commit -m "Initial commit."
$ tagit -p
No changes to repository since last tag '0.0.0'.
```

**Comment by SunSparc** [comment]
Either we insist on users performing their own initial tag, or we impose an initial tag upon them.

Tags can be manually set and changed fairly easily. Would we want to assume users always want their initial tag to be: `0.0.0`?

**Comment by mdwhatcott** [comment]
I missed the line in the README that explained about the initial tag. Maybe a code sample for "getting started with a new repo" would help. I'll maybe submit that change. Thanks
